#!/usr/bin/env bash

RESOURCE=${1-all}
MATCH='.*' 
KUBECTL_COMMAND="kubectl get $RESOURCE"

echo RESOURCE: $RESOURCE MATCH: $MATCH
echo

shift
while getopts ":m" opt; do
	case $opt in
		m) MATCH="$2" ;;
		\?) echo "Invalid option: -$OPTARG" ;;
  	esac
done


while read -r line; do
	name=${line%% *}

	if [[ -z $line || $name == NAME ]] ; then
		continue
	fi

	if [[ $name =~ $MATCH ]] ; then
		echo $name
	fi
done < <($KUBECTL_COMMAND)
