#!/usr/bin/env bash

#TODO add usage
usage(){
	echo Usage: 
}

printDebug(){
	if [[ -n $PRINT_DEBUG ]] ; then
		echo $@
		echo
	fi
}
main(){
	local MATCH='.*' 
	local SCRIPTARGS=()
	local PASSEDARGS=
	local OPTSTRING=":dnm:p:"
	local NAME_ONLY=
	while [ $OPTIND -le $# ]; do
		if getopts $OPTSTRING option; then
			case $option in
				d) PRINT_DEBUG="TRUE"
					printDebug -d="TRUE";;
				m) MATCH=$OPTARG
					printDebug -m=$OPTARG;;
				n) NAME_ONLY="TRUE";;
				p) PASSEDARGS=$OPTARG
					printDebug "-p=$OPTARG";;
				?) printDebug "? - $OPTARG ${!OPTIND} "
					local OPTVAL=${!OPTIND}
					# Assume that unidentified flags are for kubectl (PASSEDARGS)
					PASSEDARGS+=("-$OPTARG")

					# If the next arg is a flag then let getopts handle parsing
					if [[ ${OPTVAL:0:1} != '-' && -n $OPTVAL ]] ; then
						printDebug "this is an option '$OPTVAL'"
						PASSEDARGS+=("$OPTVAL")
						((OPTIND++))
					fi;;
			esac
		else
			# Handle non-flagged positional arguments and increment OPTIND
			SCRIPTARGS+=("${!OPTIND}")
			((OPTIND++))
		fi
	done
	printDebug "passedargs: ${PASSEDARGS[@]}"
	printDebug "scriptargs: ${SCRIPTARGS[@]}"

	#First positional argument is the kube resource type. Defaults to "all" if unspecified
	RESOURCE=${SCRIPTARGS[0]-all}

	#ALl other positonal arguments are dumped to kubectl command
	KUBECTL_COMMAND="kubectl get $RESOURCE"
	KUBECTL_GET_COMMAND="kubectl get"
	printDebug "RESOURCE: $KUBECTL_COMMAND MATCH: '$MATCH' NUM_SCRIPT_ARGS: ${#SCRIPTARGS} ${SCRIPTARGS[0]}"

	while read -r line; do
		NAME=${line%% *} # Name is the first column
		
		# Skip empty lines, columns, and nonmatches
		if [[ -z $line || $NAME == NAME || ! $NAME =~ $MATCH ]] ; then
			continue
		fi

		# Only print the name if -n is specified, overrides -p
		if [[ -n $NAME_ONLY ]] ; then 
			echo $NAME; continue;
		fi
		
		# Handle case where resource is "all" or comma-separated. 
		GET_COMMAND=$( \
			[[ $RESOURCE == "all" || $RESOURCE =~ ',' ]] && \
			echo "kubectl get $(echo $NAME | sed "s/\// /") ${PASSEDARGS[@]}" || \
			echo "$KUBECTL_COMMAND $NAME ${PASSEDARGS[@]}"
		)
		

		echo "# $GET_COMMAND"
		$GET_COMMAND
		echo 
	done < <($KUBECTL_COMMAND)
}

main "$@"
