#!/usr/bin/env bash

#TODO add usage
usage(){
	echo Usage: 
}

print_debug(){
	if [[ -n $PRINT_DEBUG ]] ; then
		printf "$@"
	fi
}

print_logs(){
	local kb_objects=($@)
	for kb_object in ${kb_objects[@]}; do
		command="kubectl logs $kb_object" 
		print_debug $command
		echo "# $kb_object" 
		#TODO: add flag for tail
		$command | tail -n 10
		echo
	done
}

# (expression) && cmd || cmd is used as a ternary operation
# && does not continue evaluation if the first condition is TRUE (exit code 0)

HIGHLIGHT="\e[1;30;47m"
NO_HIGHLIGHT="\e[0m"
CURSOR_INVISIBLE="\e[?25l"
CURSOR_VISIBLE="\e[?25h"
CURSOR_LINE_START="\e[E"
ERASE_END="\e[0J"
ERASE_LINE="\e[2K"

erase_lines(){
	local num_lines=$1
	
	printf $CURSOR_LINE_START # Move cursor to start of line
	#local i
	#for (( i=0; i < $num_lines; i++ )) ; do
	#	printf "\e[1A"
	#done
	printf "\e[%sA" $num_lines # Move the cursor up N lines
	
	printf $ERASE_END
}

display_resources(){
	printf $CURSOR_INVISIBLE
	local resources=($@) length=${#resources[@]}
	local selected_resources=() selected_line=0 line_end i
	local curr_line_num prev_line_num at_end_of_term
	
	# Use arrow keys to select resources for listing
	while [[ "TRUE" ]] ; do	
		unset prev_line_num
		
		for (( i=0; i < $length; i++ )); do
			# all lines except the last end in a new line
			line_end=$( (( i + 1 < $length )) && echo "\n" || echo "" ) 
			
			# set style for selected lines
			color_mode=$( [[ "${selected_resources[*]}" =~ ${resources[$i]} ]] && echo $HIGHLIGHT  || echo $NO_HIGHLIGHT )
			
			# Invert colors for the selected lines.
			if [[ i -eq selected_line ]] ; then
				printf "$color_mode>%s%b " ${resources[$i]} $NO_HIGHLIGHT 
			else
				printf "$color_mode %s%b " ${resources[$i]} $NO_HIGHLIGHT 
			fi
			
			# Get the cursor position. If it doesn't increase then we are writing lines at the end of the terminal.
			# For some reason moving up a row acts differently at the bottom of the screen
			echo -en "\e[6n" ; read -sdR CURPOS; CURPOS=${CURPOS#*[}
			curr_line_num=${CURPOS%;*}	
			# Update prev line for next pass
			pos="prev  $prev_line_num : curr $curr_line_num "
			#print_debug "$pos"
			if [[ $curr_line_num -eq $prev_line_num ]] ; then
				at_end_of_term=$curr_line_num
			fi
			
			#print_debug " | at end: $at_end_of_term"
			prev_line_num=$curr_line_num
			
			printf "%b" $line_end
		done		
		
		read -rs -n 1 key
		if [[ $key == $'\e' ]] ; then
			read -rs -n 2 key
		# Return selected_resources when enter is pressed
		elif [[ ${key} == $'\0A' ]] ; then
			reset_term
			break
		fi
		
		selected_resource=${resources[$selected_line]}

		case $key in
			'q') echo -e "\n\nQuitting" ; exit ;;
			# up: move selector up
			'[A') (( selected_line > 0 )) && (( selected_line-- )) ;; 
			# down: move selector down
			'[B') (( selected_line < $length - 1 )) && (( selected_line++ )) ;; 
			# left: deselect resource, removed fromselected_resources
			'[D') selected_resources=( "${selected_resources[@]/$selected_resource}" ) ;; 
			# right: reselect resource, add to selected_resources
			'[C') selected_resources+=( "$selected_resource" ) ;; 
			*) >/dev/null echo 'ERR bad input: $key' ; exit 1  ;;
		esac
		
		# handle end of term BS
		if [[ -n $at_end_of_term ]] && (( $at_end_of_term == $curr_line_num )) ; then
			erase_lines $(( $length  - 1))
		else 
			erase_lines $(( $length ))
		fi
		
	done
	
	
	echo
	print_logs "${selected_resources[*]}"
}

reset_term(){
	printf $ERASE_END
	printf $CURSOR_VISIBLE
	printf $NO_HIGHLIGHT
}

main(){
	local MATCH='.*' 
	local SCRIPTARGS=()
	local PASSEDARGS=
	local OPTSTRING=":hdm:p:"
	local NAME_ONLY=
	while [ $OPTIND -le $# ]; do
		if getopts $OPTSTRING option; then
			case $option in
				h) 	usage ; exit 1;;
				d) 	PRINT_DEBUG="TRUE" ;;
				m) 	MATCH=$OPTARG ;;
				p) 	PASSEDARGS=$OPTARG ;;
				?) 	local OPTVAL=${!OPTIND}
					# Assume that unidentified flags are for kubectl (PASSEDARGS)
					PASSEDARGS+=("-$OPTARG")
					# If the next arg is a flag then let getopts handle parsing
					if [[ ${OPTVAL:0:1} != '-' && -n $OPTVAL ]] ; then
						PASSEDARGS+=("$OPTVAL")
						((OPTIND++))
					fi;;
			esac
		else
			# Handle non-flagged positional arguments and increment OPTIND
			SCRIPTARGS+=("${!OPTIND}")
			((OPTIND++))
		fi
	done
	
	print_debug "DEBUG ENABLED\n"
	print_debug "MATCHING: \"$MATCH\"\n"
	print_debug "POSITIONAL ARGS: \"$SCRIPTARGS\"\n"
	print_debug "PASSED ARGS: \"$PASSEDARGS\"\n"
	
	
	#TODO: add flag for specifying location of kbget 
	#Exit if kbget not available
	if [[ ! $(which kbget) ]] ; then
		echo "kbget not found;" >&2 
		exit 1
	fi
	
	# Set default resource if none are passed
	SCRIPTARGS=${SCRIPTARGS[0]-"pod,service,deployment,statefulset"}
	local KBGET_COMMAND="kbget $SCRIPTARGS -m $MATCH -n -p $PASSEDARGS"
	print_debug "KBGET COMMAND: $KBGET_COMMAND\n"
	print_debug "\n"
	local line resource_list=() 
	
	while read line; do
		resource_list+=($line)
	done < <($KBGET_COMMAND)
	
	if [[ ${#resource_list} == 0 ]] ; then
		echo "NO RESOURCES MATCHED" >&2
		exit
	fi
	
	trap reset_term EXIT # Make cursor visible
	
	display_resources "${resource_list[*]}"
}

main "$@"