#!/usr/bin/env bash

#TODO add usage
usage(){
	echo Usage: 
}

printDebug(){
	if [[ -n $PRINT_DEBUG ]] ; then
		echo $@
		echo
	fi
}

print_logs(){
	local kb_objects=($@)
	for kb_object in ${kb_objects[@]}; do
		command="kubectl logs $kb_object" 
		printDebug $command
		echo "# $kb_object" 
		#TODO: add flag for tail
		$command | tail -n 10
		echo
	done
}

# (expression) && cmd || cmd is used as a ternary operation
# && does not continue evaluation if the first condition is TRUE (exit code 0)
display_resources(){
	local resources=($@) length=${#resources[@]}
	local selected_line=0 line_end i
		
	printf "\e[?25l" # Hide cursor
	
	# Use arrow keys to select resources for listing
	while true; do
		for (( i=0; i < $length; i++ )); do
			# all lines except the last end in a new line
			line_end=$( (( i + 1 < $length )) && echo "\n" || echo "" ) 
			
			if (( i == selected_line )) ; then
				printf ">%s%b" ${resources[$i]} $line_end
			else
				printf " %s%b" ${resources[$i]} $line_end
			fi
		done
	
		read -rs -n 1 key
		if [[ $key == $'\e' ]] ; then
			read -rs -n 2 key
		fi
		case $key in
			'q') echo QUITTING ; exit ;;
			'[A') (( selected_line > 0 )) && (( selected_line-- )) ;; # up
			'[B') (( selected_line < $length - 1 )) && (( selected_line++ )) ;; # down
			'[D') echo LEFT ;; # left
			'[C') echo RIGHT ;; # right
			*) >&2 echo 'ERR bad input'; exit 1  ;;
		esac
		
		# Rest cursor position
		printf "\e[E"
		printf "\e[%sA" $((( $length-1 )))
	done
}

main(){
	local MATCH='.*' 
	local SCRIPTARGS=()
	local PASSEDARGS=
	local OPTSTRING=":hdm:p:"
	local NAME_ONLY=
	while [ $OPTIND -le $# ]; do
		if getopts $OPTSTRING option; then
			case $option in
				h) 	usage ; exit 1;;
				d) 	PRINT_DEBUG="TRUE"
					printDebug -d="TRUE";;
				m) 	MATCH=$OPTARG
					printDebug -m=$OPTARG;;
				p) 	PASSEDARGS=$OPTARG
					printDebug "-p=\"$OPTARG\"";;
				?) 	printDebug "? - $OPTARG ${!OPTIND} "
					local OPTVAL=${!OPTIND}
					# Assume that unidentified flags are for kubectl (PASSEDARGS)
					PASSEDARGS+=("-$OPTARG")

					# If the next arg is a flag then let getopts handle parsing
					if [[ ${OPTVAL:0:1} != '-' && -n $OPTVAL ]] ; then
						printDebug "this is an option '$OPTVAL'"
						PASSEDARGS+=("$OPTVAL")
						((OPTIND++))
					fi;;
			esac
		else
			# Handle non-flagged positional arguments and increment OPTIND
			SCRIPTARGS+=("${!OPTIND}")
			((OPTIND++))
		fi
	done
	
	#TODO: add flag for specifying location of kbget 
	#Exit if kbget not available
	if [[ ! $(which kbget) ]] ; then
		echo "kbget not found;" >&2 
		exit 1
	fi
	
	# Set default resource if none are passed
	SCRIPTARGS=${SCRIPTARGS[0]-"pod,service,deployment,statefulset"}
	local KBGET_COMMAND="kbget $SCRIPTARGS -m $MATCH -n -p $PASSEDARGS"
	printDebug $KBGET_COMMAND
	local line resource_list=() 
	
	while read line; do
		resource_list+=($line)
	done < <($KBGET_COMMAND)
	
	
	display_resources "${resource_list[@]}"

}

main "$@"